services:
  blackgate:
    image: blackgate/app:latest
    container_name: blackgate
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - /var/lib/blackgate/khepri:/app/khepri
      - /tmp:/tmp
    environment:
      - DATABASE_DATA_DIR=/app/khepri
      - NODE_IP=127.0.0.1
      - RELEASE_COOKIE="Vt8gXnEI2zRH4l3eqUEBrcGQ22mHSj73CgkYm02u"
      - PHX_SERVER=true
      - PORT=4000
      - PHX_HOST=0.0.0.0
      - API_AUTH_USERNAME=admin
      - API_AUTH_PASSWORD=password123
      - LICENSE_SERVER_URL=https://license-server-eta-bay.vercel.app
      - ADMIN_SECRET=blackgate212514
      - RLIMIT_NOFILE=65536
